#https://docs.github.com/en/actions/using-workflows/reusing-workflows#example-reusable-workflow
name: Read Package Version

on:
  workflow_call:
    inputs:
      packageName:
        required: true
        type: string
      folderWithPackage:
        required: true
        type: string
    secrets:
      testsecret:
        required: true
    outputs:
      packageVersion:
        description: "The version evaluated from package"
        value: ${{ jobs.readversion.outputs.packageVersion }}
        
jobs:
  readversion:
    runs-on: ubuntu-latest

    outputs:
      packageVersion: ${{ steps.read_package_version.outputs.version  }}

    steps:
    - uses: actions/checkout@v3
    - name: Read package version
      working-directory: ${{ inputs.folderWithPackage }}
      run: |
        # See also https://gist.github.com/darrenn/8c6a5b969481725a4413
        # and https://phil.lavin.me.uk/2012/04/trimming-white-space-with-sed/
        PACKAGE_VERSION=$(cat package.json \
          | grep version \
          | head -1 \
          | awk -F: '{ print $2 }' \
          | sed 's/[",]//g' \
          | sed 's/^ *//;s/ *$//')

        echo "Pipeline is for ${{ inputs.packageName }} for version '$PACKAGE_VERSION'"
        # echo "::set-output name=version::$PACKAGE_VERSION"
        echo "version=$PACKAGE_VERSION" >> $GITHUB_OUTPUT
      id: read_package_version